import { readFileSync } from 'fs';
import { resolve } from 'path';
import { describe, expect, it } from 'vitest';

describe('swap task card Figma routing block', () => {
  it('maps the Figma routing detail row to Ionic list primitives', () => {
    const source = readFileSync(resolve(process.cwd(), 'src/components/tasks/SwapTaskCard.vue'), 'utf8');

    expect(source).toContain('gitBranchOutline');
    expect(source).toContain('routingMovementLabel(task)');
    expect(source).toContain("routingPath(task) || translate('Routing details')");
    expect(source).toContain('routingTimestamp(task)');
    expect(source).toContain('formatRoutingTimestamp(task)');
    expect(source).toContain("translate('Routing justification')");
    expect(source).toContain("routingParts.join(' > ')");
    expect(source).toContain('isSwapItemUnavailable(item)');
    expect(source).toContain("translate('Unavailable')");
    expect(source).toContain('<ion-text color="danger">');
    expect(source).toContain(":style=\"{ visibility: suggestedItemOverlineLabel(suggested) ? undefined : 'hidden' }\"");
    expect(source).toContain(':aria-hidden="!suggestedItemOverlineLabel(suggested)"');
    expect(source).toContain('<ion-text :color="suggested._isSubstitute ? \'success\' : undefined">{{ suggestedItemOverlineLabel(suggested) || \'placeholder\' }}</ion-text>');
    expect(source).not.toContain('<span v-else>');
    expect(source).toContain('function suggestedItemOverlineLabel(suggested: any): string');
    expect(source).toContain("translate('Approved swap')");
    expect(source).toContain("translate('No replacement in stock')");
    expect(source).not.toContain('swap-suggested-overline-hidden');
    expect(source).not.toContain('v-else-if="suggested._noReplacement"');
    expect(source).toContain('orderedSwapActionItem(item)');
    expect(source).toContain('_sourceOrderItemSeqId: item.orderItemSeqId');
    expect(source).toContain('chevronForwardOutline');
    expect(source).toContain('openSuggestedProductActionsPopover($event, orderedSwapActionItem(item), task)');
    expect((source.match(/<ion-list lines=\"full\"/g) ?? []).length).toBeGreaterThanOrEqual(3);
    expect(source).toContain('function productImageUrl(productId: string): string');
    expect(source).toContain('getProduct(productId)?.mainImageUrl || \'\'');
    expect(source).toContain(':src="productImageUrl(item.productId)"');
    expect(source).toContain(':src="productImageUrl(suggested.productId)"');
    expect(source).toContain(':progress-value="taskProgressValue(task)"');
    expect(source).toContain(':progress-color="task.progressColor"');
    expect(source).toContain('function taskProgressValue(task: any): number | undefined');
    expect(source).toContain('?? task.progress');
    expect(source).toContain('?? task.progressPercent');
    expect(source).toContain('?? task.completionPercentage');
    expect(source).toContain('parkOrder(task.orderId, task.shipGroupSeqId, facilityId, task.workEffortId)');
    expect(source).toContain('<ion-button fill="clear" color="primary" @click="cancelOrder(task)">{{ translate(\'Cancel order\') }}</ion-button>');
    expect(source).not.toContain("//await orderTaskStore.changeTaskStatus(task.workEffortId, 'TASK_CANCELLED')");
    expect(source).not.toContain('getProduct(item.productId).mainImageUrl');
    expect(source).not.toContain("translate('Order facility change routing')");
    expect(source).not.toContain("translate('Routing facility change description')");
    expect(source).not.toContain('<ion-grid');
    expect(source).not.toContain('<ion-row');
    expect(source).not.toContain('<ion-col');
  });
});
